server:
  port: 80
eureka:
  client:
    register-with-eureka: false
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7001
      #defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka
feign:
  hystrix:
    # 在feign中开启Hystrix
    enabled: true


hystrix:
  command:
    default:
      execution:
        isolattion:
          thrread:
            timeoutInMilliseconds: 20000
ribbon:
  ConnectTimeout: 5000            # 连接超时
  ReadTimeout: 5000               # 处理超时
  MaxAutoRetries: 1               # 重试次数
  MaxAutoRetiresNextServer: 1     # 访问集群其余节点
  OkToRetryOnAllOperations: true  # 开启重试